### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by net-tech** [ARealWant/Guildbomb-Discord-Raid-Bot#11]
Hello when I try to do 

`mainbomb.py`

it dosent work, also I get these errors 

`unable to import 'discord.ext`

`unable to import 'discord'`

![Screenshot 2021-01-29 at 16 52 52](https://user-images.githubusercontent.com/74873375/106296838-6f5ae400-6252-11eb-8325-fe464ec70fe9.jpg)

**Comment by net-tech** [comment]
I installed pip first, after that I installed python using

python3 -m pip install -U discord.py

**Comment by DuckMasterAl** [comment]
@net-tech Just letting you know, you leak your token in that screenshot.
It should be reset now because I'm posting this comment with the token in it.

Token to Invalidiate:`ODA0NzM3MzU2MDYxNjA10TM4.YBQsEA.h6vfq4hDK28Vpl5yVR2uynjY0y0`

**Comment by net-tech** [comment]
Ok, invalidated, can you help now

**Comment by DuckMasterAl** [comment]
You may be using the wrong version of python when running the code, or you may have not installed `discord.py` on the right version. Make sure to follow the [installation instructions.](https://github.com/Rapptz/discord.py#installing)

**Comment by AstroOrbis** [comment]
Do `pip3 uninstall discord.py discord.py@rewrite && pip3 install discord.py`

**Comment by AstroOrbis** [comment]
Also make sure your pip is up to date using `pip3 install --upgrade pip`

**Comment by ARealWant** [comment]
> Also make sure your pip is up to date using `pip3 install --upgrade pip`

If the problem persists after doing what @AstroOrbis has mentioned, please open a new issue in the Issue Tab.
