### ISSUE TITLE
I don't know how to do

### ISSUE THREAD

**Issue by waisenchunpro** [ARealWant/Guildbomb-Discord-Raid-Bot#8]
I don't know how to do step 6 and step 7, step 6 the invite is invalid and I don't know what do you mean change id.
Step 7, how to start a bot script IDK.
Pls teach me

**Comment by ARealWant** [comment]
Hello,

you can find the needed ID in the Discord Develops Portal, which's also mentioned in the readme.md - leave a comment if you need any further help.

Sincerely yours
ARealWant
